import Head from "next/head";
import About from "@/feature/about";
import HeroSlide from "@/components/sliders/hero-slide";
import MultimediaSlide from "@/components/sliders/multimedia-slide";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSlide />
      <About />
      <MultimediaSlide />
    </>
  );
}
